- hosts: all

  vars:
          ssh_key_filename: id_rsa
 
  tasks:
  
          - name : Create .ssh
            command: mkdir .ssh
  
          - name: generate ssh key "{{ssh_key_filename}}"
            openssh_keypair:
                    path: "~/.ssh/{{ssh_key_filename}}"
                    type: rsa
                    size: 4096
                    state: present
                    force: no
                    
