- hosts: fe1
  tasks:
    - name: Deploy waysgallery-frontend 1
      command: chdir=/home/frontend1/waysgallery-frontend/ docker-compose up -d

- hosts: fe2
  tasks:
    - name: Deploy waysgallery-frontend 2
      command: chdir=/home/frontend2/waysgallery-frontend/ docker-compose up -d

- hosts: be1
  tasks:
    - name: Deploy waysgallery-backend 1
      command: chdir=/home/backend1/waysgallery-backend/ docker-compose up -d


- hosts: be2
  tasks:
    - name: Deploy waysgallery-backend 2
      command: chdir=/home/backend2/waysgallery-backend/ docker-compose up -d
      
      
