#- hosts: jenkins
 # tasks:
  #  - name: "docker run jenkins"
   #   command: docker run -p 8080:8080 -p 50000:50000 -d -v jenkins_home:/usr/app dhanifajar15/jenkins


#- hosts: monitor
 # tasks:
  #  - name: "docker run prometheus"
   #   command: docker run -p 9090:9090 -d  dhanifajar15/prometheus

- hosts: all
  tasks:
    - name: "docker run node-exporter"
      command: docker run -d --net="host" --pid="host" -v "/:/host:ro,rslave" quay.io/prometheus/node-exporter --path.rootfs=/host

#- hosts: monitor
#  tasks:
#    - name: "docker run grafana"
#      command: docker run -d -p 3000:3000 --net=host dhanifajar15/grafana
      
- hosts: db
  tasks:
    - name: Deploy database
      command: docker run --name some-postgres -e POSTGRES_PASSWORD=wayshub -d postgres
