- hosts: all
  tasks:
    - name: "Install Docker Dependencies"
      apt:
        name:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: "Add gpg Docker Key"
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
 
    - name: "Add Docker Repo"
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable

    - name: "Install Docker Package"
      apt:
         name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          
    - name: "Install docker-compose"
      get_url: 
         url : https://github.com/docker/compose/releases/download/1.29.1/docker-compose-Linux-x86_64
         dest: /usr/local/bin/docker-compose
         mode: 0755

